name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install conan
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install conan
    - name: mkdir
      run: mkdir build && cd build
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: make
